version: 0.0
os: linux
files:
  - source: docker-compose.fullnode.main.yml
    destination: /data/tron-node/tron-docker/
hooks:
  BeforeInstall:
    - location: prepare_environment.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_service.sh
      timeout: 180
      runas: ubuntu
  ValidateService:
    - location: validate_service.sh
      timeout: 300
      runas: ubuntu
