services:
  tron-node-nile:
    container_name: tron-node
    image: java-tron:Nile_4.8.0  # Add specific tag if needed
    mem_limit: 6g
    ports:
      - "8090:8090"
      - "8091:8091"
      - "18888:18888"
      - "18888:18888/udp"
      - "50051:50051"
    volumes:
      - ./conf:/java-tron/conf
      - ./logs/nile:/java-tron/logs
      - ./output-directory/nile:/java-tron/output-directory
    command:
      - -jvm
      - "{-Xmx5g -Xms4g -XX:+UseConcMarkSweepGC}"  # Using environment variable for JVM arguments
      - -c
      - /java-tron/conf/nile_net_config.conf
