{
 "title": "java-tron-mechanism",
 "tags": [ "tron-sub-metric" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "group", "label": "group", "query": { "query": "label_values(group)" } }
  ]
 },
 "panels": [
  {
   "title": "Miner Success/H",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tron:miner_total{group=\"tron-mainnet\",instance=\"solidity86\",type=\"success\"}[$__interval])",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Miner Miss /6s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(increase(tron:miner_total{instance=\"solidity86\",type=\"miss\"}[$__interval]))",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Miner Miss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase (tron:miner_total{instance=\"solidity86\",type=\"miss\"}[$__interval])",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Miner Latency/10min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(tron:miner_latency_seconds_sum{instance=\"solidity86\"}[$__interval])/increase(tron:miner_latency_seconds_count{instance=\"solidity86\"}[$__interval])",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Vote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "tron:miner_g{instance=\"solidity86\",type=\"vote\"}",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Miner (new or del)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "tron:miner_total{instance=\"solidity86\",type=\"new\"}",
     "legendFormat": "new-{{miner}}"
    },
    {
     "expr": "tron:miner_total{instance=\"solidity86\",type=\"del\"}",
     "legendFormat": "del-{{miner}}"
    }
   ]
  },
  {
   "title": "Proposal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "tron:proposal_g{instance=\"solidity86\",type=\"vote\"}",
     "legendFormat": "{{miner}}"
    }
   ]
  }
 ]
}