{
 "title": "java-tron-api-statistic",
 "tags": [ "java-tron" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "group", "label": "group", "query": { "query": "label_values(group)" } }
  ]
 },
 "panels": [
  {
   "title": "Low Perf API Alert-getBlocksByLimitNext(http)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(tron:http_service_latency_seconds_count{group=`tron-external`,url='/wallet/getblockbylimitnext'}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Low Perf API Alert-getBlocksByLimitNext(grpc)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(tron:grpc_service_latency_seconds_count{group=`tron-external`,endpoint=`protocol.Wallet/GetBlockByLimitNext`}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Low Perf API Alert-getAssetIssueList",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(tron:internal_service_latency_seconds_count{group=`tron-external`,class=\"Wallet\",method =\"getAssetIssueList\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Low Perf API Alert-getBlockByLatestNum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(tron:internal_service_latency_seconds_count{group=`tron-external`,class=\"Wallet\",method =\"getBlockByLatestNum\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " HTTP QPS Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tron:http_service_latency_seconds_count{group=`$group`}[5m])) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "HTTP latency TP99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tron:http_service_latency_seconds_bucket{group=`$group`,instance=`$instance`}[$__interval])) by (le,url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": " GRPC QPS Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tron:grpc_service_latency_seconds_count{group=`$group`}[5m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "GRPC latency TP99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tron:grpc_service_latency_seconds_bucket{group=`$group`,instance=`$instance`}[$__interval])) by (le,endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Wallet Service TP99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tron:internal_service_latency_seconds_bucket{group=`$group`,instance=`$instance`,class=\"Wallet\"}[$__interval])) by (le,method))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}