version: '3.8'
services:
  tron-node:
    image: tronprotocol/java-tron:latest
    container_name: tron-node
    user: root
    networks:
      - tron_network
    deploy:
      resources:
        limits:
          memory: 16g
    ports:
      - "8090:8090" # for external http API request
      - "9527:9527" # used for metric API
    volumes:
      - ./conf:/java-tron/conf # ensure the config path is correct, make sure the config file metric is enabled
      - ./datadir:/java-tron/data # mount a local directory to make the block data persistent.
      - ./logs:/java-tron/logs
    command: >
      -jvm "{-Xmx12g -Xmn2g -XX:+UseConcMarkSweepGC -XX:+PrintGC -Xloggc:./logs/gc.log }" -c ./conf/main_net_config.conf

  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      - tron_network
    ports:
      - "3100:3100"
    volumes:
      - ./conf:/etc/loki
    command: >
      -config.file=/etc/loki/loki-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    networks:
      - tron_network
    volumes:
      - ./logs:/var/log
      - ./conf:/etc/promtail
    command: >
      -config.file=/etc/promtail/config.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: root
    networks:
      - tron_network
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  tron_network:
    driver: bridge
