version: '3.8'
services:
  tron-node:
    extends:
      file: tron-fullnode.yml
      service: tron-node

  node-exporter:
    extends:
      file: node-exporter.yml
      service: node-exporter

  prometheus:
    extends:
      file: prometheus.yml
      service: prometheus

  thanos-receive:
    extends:
      file: thanos-receive.yml
      service: thanos-receive

  minio:
    extends:
      file: minio.yml
      service: minio

  thanos-store:
    extends:
      file: thanos-store.yml
      service: thanos-store

  querier:
    extends:
      file: thanos-querier.yml
      service: thanos-querier

  grafana:
    extends:
      file: grafana.yml
      service: grafana
