version: '3.8'
services:
  tron-node:
    extends:
      file: tron-fullnode.yml
      service: tron-node

  node-exporter:
    extends:
      file: node-exporter.yml
      service: node-exporter

  prometheus:
    extends:
      file: prometheus.yml
      service: prometheus
