version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: root
    deploy:
      resources:
        limits:
          memory: 1g
    environment:
      - GF_METRICS_ENABLED=true  # Enable Grafana metrics exposure
    volumes:
      - ../grafana_data:/var/lib/grafana  # Grafana database and dashboards
      - ../grafana_config:/etc/grafana    #
    ports:
      - "3000:3000"
    restart: unless-stopped
