version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # Map port for API
      - "9001:9001"  # Map port for UI
    command: minio server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: melovethanos
    volumes:
      - ../minio:/data
    restart: unless-stopped  # Optional: Restart policy
