version: '3.8'
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"  # For metric collection
    volumes:
      - "./:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
    restart: unless-stopped
