version: '3.8'
services:
  thanos-store:
    image: quay.io/thanos/thanos:v0.33.0
    container_name: thanos-store
    user: root
    ports:
      - "10911:10911"  # HTTP
      - "10912:10912"  # gRPC
    volumes:
      - ../store-data:/var/thanos/store # Path relative to this file
      - ../conf:/etc/thanos
    command:
      - "store"
      - "--data-dir=/var/thanos/store"
      - "--objstore.config-file=/etc/thanos/bucket_storage.yml"
      - "--http-address=0.0.0.0:10911"
      - "--grpc-address=0.0.0.0:10912"
    restart: unless-stopped
