image:
  repository: quay.io/thanos/thanos
  tag: v0.33.0

thanosReceive:
  replicaCount: 2
  clusterName: "mainnet"
  retention: "30d" # for production suggest 30 days
  storageClass: "standard"
  storageSize: "4Gi" # enough for 6 fullnodes metrics with one month records for each replica
  resources:
    limits:
      cpu: 2000m # 2 CPU
      memory: 4Gi
    requests:
      cpu: 1000m # 1 CPU
      memory: 2Gi
