# This is a complete configuration to deploy Loki backed by a s3-compatible API, like MinIO for storage.

auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0
  grpc_listen_port: 9096
  log_level: debug
  grpc_server_max_concurrent_streams: 1000

common:
  ring:
    instance_addr: 127.0.0.1  # Address of the instance
    kvstore:
      store: inmemory # Use in-memory key-value store for the ring
  path_prefix: /loki # Prefix for storing in-memory data
  replication_factor: 1 # For monolithic deployment, the replication factor is 1


# Configures the chunk index schema and where it is stored.
schema_config:
  configs:
    - from: 2025-01-01 # The date from which the schema will be applied. For a single schema, just any past date.
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_ # Prefix for index files
        period: 24h  # Period for creating new index files

# Index files will be written locally at /loki/index and, eventually, will be shipped to the storage via tsdb-shipper.
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 48h # Default = 24h, can be increased for faster performance over longer query periods, uses more disk space
  aws:
    s3: s3://minio:melovethanos@minio.:9000/loki # The endpoint for the s3-compatible API.
    s3forcepathstyle: true # needed to recognize the above endpoint as a path-style endpoint

ingester:
  chunk_idle_period: 30m  # Flush chunks after 30 minutes of
  chunk_target_size: 1572864  # 1.5MB target before compression
  max_chunk_age: 2h  # Force flush after 2h max

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

limits_config:
  metric_aggregation_enabled: true

pattern_ingester:
  enabled: true
  metric_aggregation:
    loki_address: localhost:3100

frontend:
  encoding: protobuf
