version: '3'
services:
  querier:
    image: quay.io/thanos/thanos:v0.33.0
    container_name: querier
    user: root
    networks:
      - tron_network
    ports:
      - "9091:9091"
    command:
      - query
      - --endpoint.info-timeout=30s
      - --http-address=0.0.0.0:9091
      - --query.replica-label=replica
      - --store=thanos-receive:10907 # --store: The grpc-address of the Thanos Receive service，if Receive run remotely replace container name "thanos-receive" with the real ip
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: root
    networks:
      - tron_network
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  tron_network:
    driver: bridge
