apiVersion: v1
kind: Service
metadata:
  name: thanos-receive-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: receive
  ports:
    - name: http # for receive provide store API
      port: 10909
      targetPort: 10909
      nodePort: 30009  # Specify a NodePort within the range 30000-32767, to visit from host
      protocol: TCP
    - name: remote-write
      port: 10908
      targetPort: 10908
      nodePort: 30008
      protocol: TCP
    - name: grpc
      port: 10907
      targetPort: 10907
      nodePort: 30007
      protocol: TCP