apiVersion: v1
kind: Service
metadata:
  name: thanos-receive
  labels:
    app.kubernetes.io/component: receive
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10907
    targetPort: 10907
  selector:
    app.kubernetes.io/component: receive