apiVersion: v1
kind: Service
metadata:
  name: thanos-receive-nodeport
  namespace: default
  labels:
    app.kubernetes.io/component: receive
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: receive
  ports:
    - name: http
      port: 10909
      targetPort: 10909
      nodePort: 30009  # Specify a NodePort within the range 30000-32767
      protocol: TCP
    - name: remote-write
      port: 10908
      targetPort: 10908
      nodePort: 30008
      protocol: TCP
    - name: grpc
      port: 10907
      targetPort: 10907
      nodePort: 30007
      protocol: TCP
